"""Render the public pages to static HTML for GitHub Pages.

Usage:  python -m scripts.build_static [--out site] [--domain tcgtrending.com]

Renders the Flask pages through the test client (no server needed), so the
templates stay the single source of truth. Only public pages are built:
gainers, penny movers, losers, and a detail page for every card they link to.
Hidden pages (early movers, backtest, meta watch) and sealed data are not
published.
"""
import argparse
import json
import os
import re
import shutil

from app import create_app
from app.analysis import calculate_top_losers

PAGES = {
    "/": "index.html",
    "/penny-movers": "penny-movers/index.html",
    "/losers": "losers/index.html",
}
CARD_LINK = re.compile(r'href="(/card/\d+/[^"/]+/)"')


def refresh_losers(db_path="data/prices.db", json_path="data/top_losers.json"):
    """Losers were never regenerated by the daily run, so build them fresh."""
    losers = calculate_top_losers(db_path, limit=50)
    with open(json_path, "w") as f:
        json.dump([] if losers.empty else losers.to_dict("records"), f, indent=2)
    return len(losers)


def write(out_dir, rel_path, body):
    path = os.path.join(out_dir, rel_path)
    os.makedirs(os.path.dirname(path) or out_dir, exist_ok=True)
    with open(path, "wb") as f:
        f.write(body)


def build(out_dir="site", domain=None):
    if os.path.exists(out_dir):
        shutil.rmtree(out_dir)
    os.makedirs(out_dir)

    print(f"Refreshed {refresh_losers()} losers")
    client = create_app().test_client()

    card_urls = set()
    for url, rel_path in PAGES.items():
        response = client.get(url)
        if response.status_code != 200:
            raise SystemExit(f"ERROR: {url} returned {response.status_code}")
        body = response.data
        if b"error-box" in body:
            raise SystemExit(f"ERROR: {url} rendered an error message; not publishing")
        write(out_dir, rel_path, body)
        card_urls.update(CARD_LINK.findall(body.decode("utf-8")))

    built_cards = 0
    for url in sorted(card_urls):
        response = client.get(url)
        if response.status_code == 200:
            write(out_dir, url.strip("/") + "/index.html", response.data)
            built_cards += 1
        else:
            print(f"WARNING: skipped {url} ({response.status_code})")

    shutil.copytree("app/static", os.path.join(out_dir, "static"))
    open(os.path.join(out_dir, ".nojekyll"), "w").close()
    if domain:
        with open(os.path.join(out_dir, "CNAME"), "w") as f:
            f.write(domain + "\n")

    print(f"Built {len(PAGES)} pages and {built_cards} card pages into {out_dir}/")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="site")
    parser.add_argument("--domain", default=None)
    args = parser.parse_args()
    build(args.out, args.domain)
