name: yugioh price fetcher

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
         pip install -r requirements.txt
    
      - name: run yugioh fetcher
        run: |
          python scripts/fetch_prices.py
      
      - name: Calculate top gainers
        run: |
          python -m scripts.top_gainers
        continue-on-error: true

      - name: Commit database to repo
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/prices.db
          git diff --cached --quiet || (git commit -m "Update prices.db" && git push)
